package com.wl.technology.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wl.technology.bean.DataItem;

import com.wl.technology.dao.DataItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataItemDaoConfig;

    private final DataItemDao dataItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataItemDaoConfig = daoConfigMap.get(DataItemDao.class).clone();
        dataItemDaoConfig.initIdentityScope(type);

        dataItemDao = new DataItemDao(dataItemDaoConfig, this);

        registerDao(DataItem.class, dataItemDao);
    }
    
    public void clear() {
        dataItemDaoConfig.clearIdentityScope();
    }

    public DataItemDao getDataItemDao() {
        return dataItemDao;
    }

}
